/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    'Attack': '攻击',
    'Attack!': '攻击!',
    'and': '和',
    'Battle': '战斗',
    'Become Stronger!': '变得更强！',
    'Buy me a Coffee': '给我买杯咖啡',
    'Bonus': '加成',
    'Cancel': '取消',
    'COLOR': '颜色',
    'Copy': '复制',
    'Copy the content of text field to export (save it in your notes/text file/etc': '复制要导出的文本字段的内容（将其保存在您的笔记/文本文件/等',
    'Credits': '鸣谢',
    'Defense': '防御',
    'Hard Reset': '硬复位',
    'Global': '',
    'Global': '全局',
    'Load Game': '加载游戏',
    'Load': '加载',
    'loading': '加载中',
    'MAX': '最大',
    'OK': '好',
    'Otherwise...': '或者...',
    'Reset': '重置',
    'Reset Game': '重置游戏',
    'Skills': '技能',
    'Soul Not Found': '灵魂未找到',
    'Spirit Dungeons': '精神地牢',
    'to be one of the first to play full version of': '成为第一个玩完整版的人',
    'Upgrade a Skill': '升级1个技能',
    'Trophies': '奖杯',
    'Thanks for playing,': '感谢参与，',
    'Thanks to Florent Cailhol and Randy Tayler for helping me compress the game to 13 kilobytes for the': '感谢 Florent Cailhol 和 Randy Tayler 帮助我将游戏压缩到 13 KB',
    'This will reset all your progress and you will have to start the game over from': '这将重置您的所有进度，您将不得不重新开始游戏',
    'This action is not reversable and will override your current game progress!': '此操作不可逆，将覆盖您当前的游戏进度！',
    'souls': '灵魂',
    'for helping me playtest the game;': '帮助我测试游戏；',
    'I\'m working on a full version of the game with unique Units, Skills, Mechanics, and so much MORE!': '我正在开发具有独特单位、技能、机制等等的完整版游戏！',
    'Increases your Attack power': '增加你的攻击力',
    'Increases your Defense power': '增加你的防御力',
    'Increases your Experience gain': '增加你的经验增益',
    'Increases your Gold gain': '增加你的黄金收益',
    'Increases your Production speed that scales with stage': '增加您的生产速度与阶段的规模',
    'Increases your Skeleton power & generation speed': '增加你的骷髅力量和生成速度',
    'Increases your Zombie power & generation speed': '增加你的僵尸力量和生成速度',
    'Increases your Wight power & generation speed': '增加你的尸鬼力量和生成速度',
    'Increases your Grim Reaper power & generation speed': '增加你的死神力量和生成速度',
    'Increases your Bone Dragon power & generation speed': '增加你的骨龙力量和生成速度',
    'Increases your Vampire power & generation speed': '增加你的吸血鬼力量和生成速度',
    'Info': '信息',
    'Infuse souls and make your army stronger!': '注入灵魂，让你的军队更强大！',
    'Join my': '加入我的',
    'joining the waitlist': '加入候补名单',
    'Learning': '学习',
    'Stats': '属性',
    'Stop Battle!': '停止战斗！',
    'Stopping Battle...': '停止战斗...',
    'Thanks to': '感谢',
    'Unlocks Skeleton auto generator!': '解锁骷髅自动生成器！',
    'Unlocks Wight auto generator!': '解锁尸鬼自动生成器!',
    'Wrath': '愤怒',
    'Skeleton': '骷髅',
    'Gained': '已获得',
    'Necromancy': '通灵术',
    'Pick a Skill': '选择一个技能',
    'Prosperity': '繁荣',
    'Calm': '冷静',
    'Paste and load existing save file content.': '粘贴并加载现有的保存文件内容。',
    'Unlocks Bone Dragon auto generator!': '解锁骨龙自动生成器！',
    'Buy': '购买',
    'Pick': '选择',
    'Yes': '是',
    'No': '否',
    'Unlocks Vampire auto generator!': '解锁吸血鬼自动生成器！',
    'Morality': '道德',
    'Music and Sound by': '音乐和声音来自',
    'Icons by': '图标来自',
    'Message Me': '联系我',
    'my Discord community': '我的 Discord 社区',
    'If you like the game so far then consider': '如果您到目前为止还喜欢这款游戏，请考虑',
    'Generates experience!': '产生经验！',
    'Generates quickly!': '生成快！',
    'Gets stronger the more they stay in battle! (resets at the end of the battle': '他们在战斗中停留的时间越长，就越强大！ （战斗结束时重置',
    'Vampire': '吸血鬼',
    'Taunts enemies!': '嘲讽敌人！',
    'Wight': '尸鬼',
    'Zombie': '僵尸',
    'Unlocks Zombie auto generator!': '解锁僵尸自动生成器！',
    'This will make things easier as you keep your attributes and trophy bonuses.': '当您保留属性和奖杯奖金时，这将使事情变得更容易。',
    'Do you want to restart now?': '是否要立即重新开始？',
    'increases their Attack by 5% and speeds up their generation time': '增加他们 5% 的攻击并加快他们的生成时间',
    'increases your Damage by 5': '将你的伤害提高 5',
    'increases your EXP Gain by 2.5': '将你的经验增益提高 2.5',
    'increases your Gold Gain by 5': '将您的金币收益提高 5',
    'reduces Damage you take by 2.5': '减少你受到的伤害 2.5',
    'speeds up your Unit Production by 1% that scales with stage you\'re in but isn\'t shown in UI': '将你的单位生产速度提高 1%，随着你所处的阶段而变化，但不会显示在 UI 中',
    'Bone Dragon': '骨龙',
    'Grim Reaper': '死神',
    'that increases your gold and experience gain as well as attack, defense and skill power!': '这会增加您的金币和经验获取以及攻击力、防御力和技能强度！',
    'This bonus is kept between resets (mini prestiges).': '该奖励在重置之间保留（迷你声望）。',
    '1.5% Global Bonus (T2 - 10%, T3 - 100': '1.5% 全局加成（T2 - 10%，T3 - 100',
    'Each T1 trophy gives you': '每个T1奖杯都给你',
    'Base Health': '基础生命值',
    'Taken Damage Reduced To': '受到的伤害减少到',
    'Unlocks Grim Reaper auto generator!': '解锁死神自动生成器！',
    'All current game progress will be LOST! Are you sure?': '所有当前的游戏进度都将丢失！ 你确定吗？',
    'formerly know as': '以前称为',
    'Can only be attacked by flying units! (Wights and Bone Dragons': '只能被飞行单位攻击！ （尸鬼和骨龙',
    'Clearing souls from the unit only removes its color but leaves the damage bonus': '从单位清除灵魂只会去除其颜色，但会留下伤害加成',
    'Each soul you infuse in your unit raises its base attack and defense stats by 1% as well as changes the color of the unit based on which color soul you infuse': '你注入的每一个灵魂都会使它的基础攻击和防御属性提高 1%，并根据你注入的灵魂颜色改变单位的颜色',
    'Generates skeletons!': '生成骷髅！',
    'Higher stages yield higher chance to get souls': '更高的阶段有更高的机会获得灵魂',
    'When 51 souls have been infused - color won\'t change anymore but souls will still be consumed to increase attack and defense stats by 1% for each soul': '注入51个灵魂时-颜色不再变化，但仍会消耗灵魂，每个灵魂增加1％的攻击和防御属性',
    'This will erase all souls from this unit but will keep the attack and defense bonus': '这将清除该单位的所有灵魂，但会保留攻击和防御加值',
    'lvl': '等级',
    'Unlocks Bone Dragon glow and improves their defense based on current stage!': '解锁骨龙之光，并根据当前阶段提高他们的防御！',
    'Unlocks Grim Reaper glow and ability to attack flying units!': '解锁死神之光和攻击飞行单位的能力！',
    'Unlocks Skeleton glow and ability to attack flying units!': '解锁骷髅之光和攻击飞行单位的能力！',
    'Unlocks Vampire glow, improves their defense based on current stage and ability to attack flying units!': '解锁吸血鬼之光，根据当前阶段提高他们的防御和攻击飞行单位的能力！',
    'Unlocks Wight glow and improves their experience gain based on souls infused and stage reached!': '根据注入的灵魂和达到的阶段，解锁 尸鬼之光 并提高他们的经验获取！',
    'Unlocks Zombie glow and improves their defense based on current stage!': '解锁僵尸之光并根据当前阶段提高他们的防御！',
    'blue souls': '蓝色灵魂',
    'Chelsea Gem': '切尔西宝石',
    'Conifer': '针叶树',
    'Cornflower Blue': '矢车菊蓝',
    'Deep Blush': '深腮红',
    'Delapouite': '德拉普伊特',
    'directly': '直接',
    'Endeavour': '奋进号',
    'Fountain Blue': '喷泉蓝',
    'green and': '绿色和',
    'Green Haze': '绿雾',
    'Infuse all units with': '为所有单位注入',
    'Infuse two units with': '为2个单位注入',
    'Infuse unit with': '为单位注入',
    'Lorc': '洛尔克',
    'Red WTF': '红色WTF',
    'red,': '红色,',
    'Screamin\' Green': '尖叫绿色',
    'Silver Chalice': '银圣杯',
    'souls accordingly': '相应的灵魂',
    'The Enemy': '敌人',
    'The Hound': '猎犬',
    'The Portal': '门户',
    'The Rainbow': '彩虹',
    'Thunderbird': '雷鸟',
    'Wild Willow': '野柳',
    '🥳 Congratulations! 🥳': '🥳 恭喜你! 🥳',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //树游戏
    'Martin Tale': 'Martin Tale',
    'Decade Jam': 'Decade Jam',
    'Cade Conkle': 'Cade Conkle',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "lvl ": "等级 ",
    "Tier ": "层 ",
    "Trophies - ": "奖杯 - ",
    "Stage #": "阶段 #",
    "Stats (": "属性点 (",
    "Reach Morality (": "达到道德 (",
    "Current Damage (Base: ": "当前伤害 (基础: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)k$/,
    /^([\d\.]+)t$/,
    /^([\d\.]+)m$/,
    /^([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Gain (.+) Defense \((.+)$/, '获得 $1 防御 \($2'],
    [/^Gain (.+) Attack \((.+)$/, '获得 $1 攻击 \($2'],
    [/^Gain (.+) souls \((.+)$/, '获得 $1 灵魂 \($2'],
    [/^Gain (.+) Gold \((.+)$/, '获得 $1 黄金 \($2'],
    [/^Infuse (.+) souls into Zombies \((.+)$/, '将 $1 灵魂注入僵尸 \($2'],
    [/^Infuse (.+) souls into Wights \((.+)$/, '将 $1 灵魂注入尸鬼 \($2'],
    [/^Infuse (.+) souls into Bone Dragons \((.+)$/, '将 $1 灵魂注入骨龙 \($2'],
    [/^Infuse (.+) souls into Skeletons \((.+)$/, '将 $1 灵魂注入骷髅 \($2'],
    [/^Infuse (.+) souls into Grim Reapers \((.+)$/, '将 $1 灵魂注入死神 \($2'],
    [/^Infuse (.+) souls into Vampires \((.+)$/, '将 $1 灵魂注入吸血鬼 \($2'],
    [/^Reach Level (.+) \((.+)$/, '达到等级 $1 \($2'],
    [/^Upgrade Skills (.+) Times \((.+)$/, '升级技能 $1 次 \($2'],
    [/^Beat Stage (.+)$/, '击败阶段 $1'],
    [/^Time to Generate \(Base: (.+) per (.+) sec$/, '生成时间（基础：每 $2 秒 $1'],
    [/^Kill (.+) Enemy Units \((.+)$/, '杀死 $1 敌方单位 \($2'],
    [/^Resurrect (.+) Vampires \((.+)$/, '复活 $1 吸血鬼 \($2'],
    [/^Resurrect (.+) Bone Dragons \((.+)$/, '复活 $1 骨龙 \($2'],
    [/^Resurrect (.+) Grim Reapers \((.+)$/, '复活 $1 死神 \($2'],
    [/^Resurrect (.+) Wights \((.+)$/, '复活 $1 尸鬼 \($2'],
    [/^Resurrect (.+) Skeletons \((.+)$/, '复活 $1 骷髅 \($2'],
    [/^Resurrect (.+) Zombies \((.+)$/, '复活 $1 僵尸 \($2'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.]+) p\/sec$/, '$1 p\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);